spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: coupon-route
          uri: lb://mall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: ware-route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: product-route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: third-party-route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
        - id: member-route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        - id: mall-host-route
          uri: lb://mall-product
          predicates:
            - Host=mall.com,item.mall.com
        - id: mall-host-search-route
          uri: lb://mall-search
          predicates:
            - Host=search.mall.com
        - id: mall-host-auth-route
          uri: lb://mall-auth-server
          predicates:
            - Host=auth.mall.com
        - id: mall-cart-route
          uri: lb://mall-cart
          predicates:
            - Host=cart.mall.com
        - id: mall-seckill-route
          uri: lb://mall-seckill
          predicates:
            - Host=seckill.mall.com



  application:
    name: mall-gateway