spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.56.42:3306/gulimall_pms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-product
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.42

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 8081
alibaba:
  cloud:
    access-key: LTAI5t6Bh5ppb4FmnwkDBrbX
    secret-key: mbxIUGLkiFdEHJOaIh4NSC9pUlKwu8
    oss:
      endpoint: https://oss-cn-shanghai.aliyuncs.com
