spring:
  #  datasource:
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    username: root
  #    password: root
  #    url: jdbc:mysql://192.168.56.42:3306/gulimall_sms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: mall-seckill
  thymeleaf:
    cache: false
  redis:
    host: 192.168.56.42
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50
  session:
    store-type: redis
  rabbitmq:
    virtual-host: /
    host: 192.168.56.42
server:
  port: 8092